/**
 * Adapts the live backend DemoViewModel (GET /api/app) into the projection
 * shape the screens render, plus a LiveState side-channel for surfaces that
 * only exist against the live backend (agent insights, data health, reviews).
 *
 * Numbers are never computed here: every value is copied verbatim from the
 * backend's typed facts; only display prose is assembled. Structural types are
 * declared locally and defensively because the generated OpenAPI contract is
 * regenerated by the backend build.
 */

import type {
  CitedText,
  ClientPreRead,
  MondayBriefProjection,
  RankedClient,
} from "../preview-contracts";

interface LiveClaim {
  id: string;
  text: string;
  citations: string[];
  authorship?: string;
}

export interface LiveInsight {
  signal_id: string;
  score: number;
  components: Record<string, number>;
  facts: LiveClaim[];
  /** The backend emits a Claim here; the adapter flattens it to its text. */
  why_it_matters?: string | LiveClaim;
  change_status?: string;
}

export function claimText(
  value: string | LiveClaim | null | undefined,
): string | undefined {
  if (!value) return undefined;
  return typeof value === "string" ? value : value.text;
}

interface LiveTypedFact {
  id: string;
  client_id: string;
  kind: string;
  value: number;
  unit: string;
  currency: string | null;
  inputs: Record<string, unknown>;
  evidence_ids: string[];
  as_of?: string;
  confidence?: number;
}

interface MemoryCardSection {
  claims: LiveClaim[];
  evidence_gap?: string | null;
}

export interface CommunicationRecord {
  id: string;
  client_id: string;
  source: "gmail" | "outlook" | "teams" | "notes" | "calendar";
  occurred_at: string;
  retrieved_at?: string;
  scheduled_at?: string | null;
  participants: string[];
  text: string;
  topics?: string[];
  provenance?: string;
  availability?: string;
  client_name?: string;
}

interface LiveClientView {
  header: {
    client_id: string;
    client_name: string;
    rm_name?: string;
    base_currency?: string;
    risk_profile?: string;
    life_stage?: string;
    reporting_language?: string;
    booking_centre?: string;
  };
  insights: LiveInsight[];
  meeting_brief: {
    sections: {
      summary: LiveClaim[];
      opening: LiveClaim;
      talking_points: LiveClaim[];
      questions: LiveClaim[];
      uncertainty: LiveClaim[];
    };
  } | null;
  brief_version: number;
  memory_card: Record<string, MemoryCardSection> | null;
  data_tab: Record<string, LiveTypedFact[]>;
  memory_tab: CommunicationRecord[];
  brief_status: string;
  verification: { passed?: boolean } | null;
  context_issues: string[];
}

interface LiveRankedClient {
  client_id: string;
  name: string;
  score: number;
  urgency: "now" | "soon" | "watch";
  meeting: string | null;
  reason: string;
}

export interface DemoViewModel {
  as_of: string;
  run_id: string;
  refreshed_at: string;
  data_health: string;
  clients: Record<string, LiveClientView>;
  calendar: unknown[];
  evidence: Record<string, Record<string, unknown>>;
  connected_evidence: Record<
    string,
    { chunk?: { id: string; record_id: string; text: string } }
  >;
  reviews: unknown[];
  ranking?: LiveRankedClient[];
}

export interface LiveState {
  runId: string;
  refreshedAt: string;
  dataHealth: string;
  briefVersions: Record<string, number>;
  briefStatus: Record<string, string>;
  verified: Record<string, boolean>;
  insights: Record<string, LiveInsight[]>;
  memoryRecords: Record<string, CommunicationRecord[]>;
  /** Per-signal caveat claims, kept separate so cards match only their own. */
  uncertaintyClaims: Record<string, CitedText[]>;
}

/**
 * Whether a citation addresses this fact, directly or via a sibling numeric
 * field of the same concept (…:mandate-gap:gap_pct cites …:mandate-gap:*).
 */
export function citesFact(citations: string[], factId: string): boolean {
  const factSegments = factId.split(":");
  const factBase = factSegments.slice(0, -1).join(":");
  return citations.some((citation) => {
    if (citation === factId) return true;
    const segments = citation.split(":");
    return (
      segments.length >= 4 &&
      segments.length === factSegments.length &&
      segments.slice(0, -1).join(":") === factBase
    );
  });
}

export type AppProjection = MondayBriefProjection & { live?: LiveState };

const MONEY = (currency: string | null | undefined, value: unknown) => {
  const amount =
    typeof value === "number"
      ? value.toLocaleString("en-SG", { maximumFractionDigits: 0 })
      : String(value);
  return currency ? `${currency} ${amount}` : amount;
};

/** Base concept behind a typed fact id such as CL-0003:fact:change-1:delta. */
function factConcept(id: string): { base: string; key: string } {
  const parts = id.split(":");
  const base = parts.slice(0, -1).join(":");
  const key = parts[parts.length - 2] ?? "";
  return { base, key };
}

function factKind(key: string): string {
  if (key.startsWith("change")) return "change";
  return key.replaceAll("-", "_");
}

function factProse(kind: string, numbers: Record<string, unknown>): string {
  switch (kind) {
    case "profile":
      return `${String(numbers.name)} · ${String(numbers.life_stage)} · risk tolerance ${String(numbers.risk_tolerance_score ?? "n/a")}.`;
    case "change":
      return `${String(numbers.instrument)} moved ${MONEY(numbers.currency as string, numbers.delta)} between snapshots.`;
    case "mandate_gap":
      return `${String(numbers.asset_class)} is ${String(numbers.actual_pct)}% against a ${String(numbers.limit_pct)}% ${String(numbers.boundary)}.`;
    case "deadline":
      return `${String(numbers.description ?? "Planned cash need")}: ${MONEY(numbers.currency as string, numbers.amount)} due in ${String(numbers.days)} days.`;
    case "facility":
      return `Facility LTV ${String(numbers.ltv_pct)}% against the ${String(numbers.trigger_pct)}% margin-call trigger.`;
    case "concentration":
      return `Largest position is ${String(numbers.weight_pct)}% of the portfolio (${MONEY(null, numbers.value)}).`;
    default:
      return Object.entries(numbers)
        .map(([field, value]) => `${field} ${String(value)}`)
        .join(", ");
  }
}

function confidence(value: number | undefined): "high" | "medium" | "low" {
  if (value === undefined || value >= 0.9) return "high";
  return value >= 0.5 ? "medium" : "low";
}

const GROUP_ORDER = [
  "allocation",
  "snapshot_changes",
  "mandate",
  "cash_need",
  "collateral",
  "liquidity",
];

/** One preview-style fact per concept, first-typed-id wins for citations. */
function adaptFacts(view: LiveClientView): MondayBriefProjection["facts"][string] {
  const byBase = new Map<
    string,
    { fact: LiveTypedFact; key: string; ids: string[] }
  >();
  const groups = GROUP_ORDER.filter((group) => group in view.data_tab).concat(
    Object.keys(view.data_tab).filter((group) => !GROUP_ORDER.includes(group)),
  );
  for (const group of groups) {
    for (const fact of view.data_tab[group] ?? []) {
      const { base, key } = factConcept(fact.id);
      const existing = byBase.get(base);
      if (existing) existing.ids.push(fact.id);
      else byBase.set(base, { fact, key, ids: [fact.id] });
    }
  }
  const facts = [...byBase.values()].map(({ fact, key }) => {
    const kind = factKind(key);
    return {
      id: fact.id,
      kind,
      what: factProse(kind, fact.inputs),
      numbers: fact.inputs,
      source_rows: fact.evidence_ids,
      event_ids: [],
      confidence: confidence(fact.confidence),
    };
  });
  // Profile leads, mirroring the fixture's source order.
  facts.sort((a, b) =>
    a.kind === "profile" ? -1 : b.kind === "profile" ? 1 : 0,
  );
  return facts as unknown as MondayBriefProjection["facts"][string];
}

/** Nicer names for the typed-fact fields the backend cites verbatim. */
const FIELD_LABEL: Record<string, string> = {
  "deadline.amount": "Planned cash need",
  "deadline.amount_in_portfolio_currency": "Cash need in portfolio currency",
  "deadline.days": "Days until cash need",
  "deadline.daily_liquid": "Daily-liquid assets",
  "deadline.coverage_pct": "Liquidity coverage",
  "facility.ltv_pct": "Facility LTV",
  "facility.trigger_pct": "Margin-call trigger",
  "facility.gap_pct": "LTV headroom",
  "concentration.value": "Largest position value",
  "concentration.weight_pct": "Largest position weight",
  "mandate-gap.actual_pct": "Actual allocation",
  "mandate-gap.limit_pct": "Mandate limit",
  "mandate-gap.gap_pct": "Mandate gap",
};

const RAW_FIELD =
  /([a-z][a-z0-9-]*)\.([a-z][a-z0-9_]*):\s*(-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)(\s[A-Z]{3})?\.?/g;

/**
 * Facts without an authored description reach briefs as "kind.field: value"
 * (sometimes embedded mid-sentence, sometimes in exponent notation); rewrite
 * every occurrence into a readable label with a formatted value.
 */
export function humanizeClaimText(text: string): string {
  return text.replace(RAW_FIELD, (_match, kind, field, number, currency) => {
    const key = `${kind}.${field}`;
    const label =
      FIELD_LABEL[key] ??
      (() => {
        const words = `${kind} ${field}`
          .replaceAll("-", " ")
          .replaceAll("_", " ");
        return words.charAt(0).toUpperCase() + words.slice(1);
      })();
    const numeric = Number(number);
    const value = currency
      ? `${String(currency).trim()} ${numeric.toLocaleString("en-SG")}`
      : field.endsWith("_pct")
        ? `${numeric}%`
        : field === "days"
          ? `${numeric} days`
          : numeric.toLocaleString("en-SG");
    return `${label}: ${value}.`;
  });
}

function cited(claim: LiveClaim): CitedText {
  return { text: humanizeClaimText(claim.text), citations: claim.citations ?? [] };
}

/**
 * The pre-read type carries one uncertainty entry; the first claim stands in
 * for it while the full per-signal list travels on LiveState.uncertaintyClaims.
 */
function leadUncertainty(claims: LiveClaim[]): CitedText {
  if (claims.length === 0)
    return { text: "No open uncertainty recorded.", citations: [] };
  return cited(claims[0]);
}

function noteIdOf(claimId: string): string {
  // memory:<topic>:notes:N-005#<hash>:<span> -> N-005
  const match = /notes:([A-Za-z0-9-]+)/.exec(claimId);
  return match ? match[1] : claimId;
}

function adaptPreRead(view: LiveClientView): ClientPreRead {
  const sections = view.meeting_brief?.sections;
  const card = view.memory_card ?? {};
  const advice = card.advice_notes?.claims?.[0];
  const gapMatch = advice
    ? /Data says: (.*?) RM note records: "(.*?)"/.exec(advice.text)
    : null;
  // Memory-card sections cite overlapping note chunks; keep each statement once.
  const seenBeliefs = new Set<string>();
  const beliefs = [
    ...(card.stated_needs_and_goals?.claims ?? []),
    ...(card.who_they_are?.claims ?? []),
  ]
    .filter((claim) => {
      if (seenBeliefs.has(claim.text)) return false;
      seenBeliefs.add(claim.text);
      return true;
    })
    .map((claim) => ({
      id: claim.id,
      note_id: noteIdOf(claim.id),
      text: claim.text,
      citations: claim.citations?.length ? claim.citations : [claim.id],
    }));
  return {
    client_id: view.header.client_id,
    name: view.header.client_name,
    language: view.header.reporting_language ?? "English",
    what_changed: view.insights.map((insight) =>
      cited(insight.facts[0] ?? { id: "", text: insight.signal_id, citations: [] }),
    ),
    gap: {
      id: advice?.id ?? `${view.header.client_id}:gap`,
      belief: gapMatch?.[2] ?? "No recorded client statement.",
      data: humanizeClaimText(
        gapMatch?.[1] ?? view.insights[0]?.facts[0]?.text ?? "",
      ),
      citations: advice?.citations ?? [],
    },
    rules_money: (sections?.talking_points ?? []).map(cited),
    opening: sections?.opening
      ? cited(sections.opening)
      : { text: "No opening prepared.", citations: [] },
    uncertainty: leadUncertainty(sections?.uncertainty ?? []),
    beliefs,
    workflow: [],
  };
}

const SOURCE_KIND: Record<CommunicationRecord["source"], string> = {
  notes: "RM note",
  gmail: "Gmail message",
  outlook: "Outlook message",
  calendar: "Calendar event",
  teams: "Teams message",
};

/**
 * The live memory_tab mixes CommunicationRecords with legacy raw note rows
 * that duplicate the same notes; only real records carry id + source.
 */
function communicationRecords(
  records: CommunicationRecord[] | undefined,
): CommunicationRecord[] {
  return (records ?? []).filter(
    (record) =>
      typeof record.id === "string" && typeof record.source === "string",
  );
}

/** Memory records become drawer-renderable evidence rows keyed by record id. */
function memoryEvidence(
  records: CommunicationRecord[],
): MondayBriefProjection["evidence"] {
  const evidence: MondayBriefProjection["evidence"] = {};
  for (const record of records) {
    evidence[record.id] = {
      id: record.id,
      kind: SOURCE_KIND[record.source] ?? record.source,
      title: record.id,
      source:
        record.provenance === "dataset" ? "data/rm_notes.json" : record.source,
      record: {
        client_id: record.client_id,
        note: record.text,
        note_id: record.id.split(":").pop(),
        note_date: (record.scheduled_at ?? record.occurred_at).slice(0, 10),
        channel: SOURCE_KIND[record.source] ?? record.source,
        rm_name: record.participants.join(", "),
        availability: record.availability ?? "Cached",
      },
    };
  }
  return evidence;
}

function fallbackRanking(viewModel: DemoViewModel): RankedClient[] {
  return Object.values(viewModel.clients)
    .map((view) => {
      const top = view.insights[0];
      const score = top?.score ?? 0;
      return {
        client_id: view.header.client_id,
        name: view.header.client_name,
        score,
        components: { gap: 0, deadline: 0, consequence: score },
        meeting: null,
        meeting_source: null,
        reason: humanizeClaimText(
          claimText(top?.why_it_matters) ??
            top?.facts[0]?.text ??
            "No open signals this run.",
        ),
        urgency: (score >= 100 ? "now" : score >= 60 ? "soon" : "watch") as
          | "now"
          | "soon"
          | "watch",
        citations: top?.facts.flatMap((fact) => fact.citations ?? []) ?? [],
      };
    })
    .sort((a, b) => b.score - a.score || a.client_id.localeCompare(b.client_id));
}

function adaptRanking(viewModel: DemoViewModel): RankedClient[] {
  if (!Array.isArray(viewModel.ranking) || viewModel.ranking.length === 0)
    return fallbackRanking(viewModel);
  return viewModel.ranking.map((entry) => {
    const top = viewModel.clients[entry.client_id]?.insights[0];
    return {
      client_id: entry.client_id,
      name: entry.name,
      score: entry.score,
      components: { gap: 0, deadline: 0, consequence: entry.score },
      meeting: entry.meeting,
      meeting_source: entry.meeting ? "calendar" : null,
      reason: entry.reason,
      urgency: entry.urgency,
      citations: top?.facts.flatMap((fact) => fact.citations ?? []) ?? [],
    };
  });
}

export function isDemoViewModel(payload: unknown): payload is DemoViewModel {
  return Boolean(
    payload &&
      typeof payload === "object" &&
      "run_id" in payload &&
      "clients" in payload &&
      "data_health" in payload,
  );
}

export function adaptViewModel(viewModel: DemoViewModel): AppProjection {
  const facts: MondayBriefProjection["facts"] = {};
  const preReads: MondayBriefProjection["pre_reads"] = {};
  const evidence: MondayBriefProjection["evidence"] = {
    ...(viewModel.evidence as unknown as MondayBriefProjection["evidence"]),
  };
  const live: LiveState = {
    runId: viewModel.run_id,
    refreshedAt: viewModel.refreshed_at,
    dataHealth: viewModel.data_health,
    briefVersions: {},
    briefStatus: {},
    verified: {},
    insights: {},
    memoryRecords: {},
    uncertaintyClaims: {},
  };
  for (const [clientId, view] of Object.entries(viewModel.clients)) {
    const records = communicationRecords(view.memory_tab);
    facts[clientId] = adaptFacts(view);
    preReads[clientId] = adaptPreRead(view);
    Object.assign(evidence, memoryEvidence(records));
    live.briefVersions[clientId] = view.brief_version;
    live.briefStatus[clientId] = view.brief_status;
    live.verified[clientId] = Boolean(view.verification?.passed);
    live.insights[clientId] = (view.insights ?? []).map((insight) => ({
      ...insight,
      why_it_matters:
        typeof insight.why_it_matters === "object" && insight.why_it_matters
          ? {
              ...insight.why_it_matters,
              text: humanizeClaimText(insight.why_it_matters.text),
            }
          : insight.why_it_matters
            ? humanizeClaimText(insight.why_it_matters)
            : insight.why_it_matters,
      facts: insight.facts.map((claim) => ({
        ...claim,
        text: humanizeClaimText(claim.text),
      })),
    }));
    live.memoryRecords[clientId] = records;
    live.uncertaintyClaims[clientId] = (
      view.meeting_brief?.sections.uncertainty ?? []
    ).map(cited);
  }
  for (const [chunkId, entry] of Object.entries(
    viewModel.connected_evidence ?? {},
  )) {
    if (!entry?.chunk || evidence[chunkId]) continue;
    evidence[chunkId] = {
      id: chunkId,
      kind: "Memory excerpt",
      title: entry.chunk.record_id,
      source: "client memory",
      record: { text: entry.chunk.text },
    };
  }
  return {
    schema_version: 1,
    as_of: viewModel.as_of,
    pipeline: ["ingest", "validate", "clean", "analytics", "agents", "verify"],
    ranking_formula:
      "Backend ranking: strongest verified signal per client, deadline-weighted.",
    ranking: adaptRanking(viewModel),
    facts,
    pre_reads: preReads,
    scenarios: {},
    evidence,
    live,
  };
}
